### ISSUE TITLE
Finds Other Console on Network

### ISSUE THREAD

**Issue by gary-hammer** [pjpeartree/rainmachine-gw1000#1]
When I first installed, the GW1000 was found and used.
Today it has found a different console and has failed to update.
I have an Ambient 2902A and WS2000 console in addition to the GW1000.

It might be a good additional to check for the GW1000 or to allow manual configuration of the IP address.

**Comment by pjpeartree** [comment]
@gary-hammer thank you for reporting this issue.
Fixed by https://github.com/pjpeartree/rainmachine-ecowitt/commit/e1cfad2bc8cf3571117181558b9dca595899aa4a
